name: CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Invoke-Build
        shell: powershell
        run: |
          Install-Module InvokeBuild -Force -Scope CurrentUser -Repository PSGallery

      - name: Install Pester
        shell: powershell
        run: |
          Install-Module Pester -Force -Scope CurrentUser -Repository PSGallery

      - name: Run build
        shell: powershell
        run: |
          Invoke-Build
